# Generated by Django 3.2.5 on 2021-07-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='tean',
            field=models.BooleanField(default=True),
        ),
    ]
