# Generated by Django 3.2.5 on 2021-07-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_person_tean'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_date_year',
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
