# Generated by Django 3.2.5 on 2021-07-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_person_birth_date_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='tean',
            field=models.BooleanField(default=False),
        ),
    ]
