# Generated by Django 3.2.5 on 2021-07-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_person_tean'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='postal_code',
            field=models.CharField(default='AB', max_length=10),
        ),
    ]
