# Generated by Django 3.2.5 on 2021-07-23 11:27

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_person_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='can_donate_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 17, 11, 27, 26, 756906, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='person',
            name='last_dontaed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
