# Generated by Django 3.2.5 on 2021-07-23 11:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210723_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='can_donate_on',
            field=models.DateField(default=datetime.datetime(2021, 9, 17, 11, 28, 15, 648753, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_dontaed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
