# Generated by Django 3.2.5 on 2021-07-23 11:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210723_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='can_donate_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 17, 11, 29, 26, 145115, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_dontaed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
