# Generated by Django 3.2.5 on 2021-07-24 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210723_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='can_donate_on',
        ),
    ]
