# Generated by Django 3.2.5 on 2021-07-24 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_person_can_donate_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='last_dontaed',
            new_name='last_donated',
        ),
    ]
