# Generated by Django 3.2.5 on 2021-07-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_last_dontaed_person_last_donated'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodbag_set', models.IntegerField()),
                ('goal', models.IntegerField()),
                ('existent_amount', models.IntegerField()),
            ],
        ),
    ]
