# Generated by Django 3.2.5 on 2021-07-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_bloodbank_existent_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='job',
            field=models.CharField(default='DEV', max_length=50),
        ),
    ]
