# Generated by Django 3.2.5 on 2021-07-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_person_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Kessy', max_length=50)),
                ('pet_type', models.CharField(max_length=50)),
            ],
        ),
    ]
