# Generated by Django 3.1.7 on 2021-08-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_related', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_date',
            field=models.DateField(default='2020-08-08'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='shipped_date',
            field=models.DateField(default="2020-03-06"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
